apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-engine
  template:
    metadata:
      labels:
        app: nexus-engine
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 5; done']
      containers:
      - name: nexus-engine
        image: varun123jjsdj/nexus-engine:latest
        command: ["node", "engine.js"]
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"
        envFrom:
        - secretRef:
            name: nexus-secret
